version: '3.8'

services:
  app:
    container_name: laufevent_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "44320:44320"
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:44320
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
